apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ default (printf "%s-pvc" .Release.Name) .Values.pvcName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentStorage }}
  storageClassName: do-block-storage
