services:
  ipt:
    image: gbif/ipt:3.3.2
    platform: linux/amd64
    # Uncomment for local testing
    # volumes: 
    #   - ./data:/srv/ipt

  ipt-sidecar:
    build: ./sidecar
    image: gbifnorway/ipt-sidecar:latest
    platform: linux/amd64
    # Uncomment for local testing
    # env_file:
    #   - .env
    # volumes:
    #   - ./data:/srv/ipt

