version: '3'

services:
  ipt:
    build: ./ipt
    image: gbifnorway/ipt-s3:latest
    platform: linux/amd64
    volumes:
      - ./data:/srv/ipt

  ipt-sidecar:
    build: ./sidecar
    image: gbifnorway/ipt-sidecar:latest
    platform: linux/amd64
    env_file:
      - .env
    volumes:
      - ./data:/srv/ipt


