# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: test-ipt-debug-service
  namespace: default
spec:
  selector:
    app: test-ipt-debug-service
  type: ClusterIP
  ports:
  - name: test-ipt-debug-service
    protocol: TCP
    port: 8000
    targetPort: 8000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ingress-nginx
data:
  30000: "default/test-ipt-debug-service:8000"

