#!/bin/bash

echo "$(date -I) Sync starting" >> /var/log/sync.log
# Copy only the /resources/*/sources txt files from remote to local
# Then sync remote back to local so that we have a backup of any files generated from the IPT's auto publish process
# ✓ Case 1: No new corema files on bucket - no effect
# ✓ Case 2: New corema files on bucket - the local files will get overwritten with `copy`
# ✓ Case 3: No new publication files generated by IPT - no effect
# ✓ Case 4: New publication files generated by IPT - the bucket files will get overwritten with `sync`
rclone copy --include "/resources/*/sources/**/*.txt" --update "sigma2:$S3_BUCKET_NAME" $IPT_DATA_DIR && \
rclone sync --update --delete-during --verbose --transfers 10 --checkers 10 --contimeout 60s --timeout 300s --retries 5 --low-level-retries 10 --exclude .~tmp~/ $IPT_DATA_DIR sigma2:$S3_BUCKET_NAME && \
echo "$(date -I) Sync complete succesfully" >> /var/log/sync.log
